version: "3"

services:
  db:
    image: postgres:12-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./src/pre-start/env/.env.development
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    image: alpine-node:12
    container_name: web
    depends_on:
      - db
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
